doc/baremetal/linker.rst: Add memory map for HSDK and HSDK-4xD
foss-for-synopsys-dwc-arc-processors/toolchain pull request #438
Opened 2021-10-15 11:59 UTC by vkremneva

2021-10-15 12:08 UTC, claziss requested changes

2021-10-15 12:08 UTC, claziss commented on doc/baremetal/linker.rst
> +    PROVIDE (__stack_top = (0xffffffff & -4 ));
you don't need this

2021-10-15 12:08 UTC, claziss commented on doc/baremetal/linker.rst
> +    PROVIDE (__end_heap =  (0xffffffff ));
nor this

2021-10-15 12:08 UTC, claziss commented on doc/baremetal/linker.rst
> +    PROVIDE (__stack_top = (0x8003ffff & -4 ));
same

2021-10-15 12:08 UTC, claziss commented on doc/baremetal/linker.rst
> +    PROVIDE (__stack_top = (0xafffffff & -4 ));
same

2021-10-15 12:08 UTC, claziss commented on doc/baremetal/linker.rst
> +    PROVIDE (__stack_top = (0x6000ffff & -4 ));
same

2021-10-15 12:33 UTC, vkremneva commented on doc/baremetal/linker.rst
> +    PROVIDE (__stack_top = (0x6000ffff & -4 ));
Should I also remove those sections from previous version of this file? https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/blame/arc-releases/doc/baremetal/linker.rst#L88

2021-10-18 10:17 UTC, vkremneva commented
@claziss I made changes that you requested, could you please take a look?

2021-10-18 11:30 UTC, claziss approved these changes

2021-10-18 11:48 UTC, abrodkin approved these changes

2021-10-18 11:49 UTC, merged